import 'dotenv/config';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import {connectDB} from '../config/db.js';
import User from '../models/User.js'; import Project from '../models/Project.js'; import ProjectMember from '../models/ProjectMember.js'; import Task from '../models/Task.js'; import Sprint from '../models/Sprint.js'; import Issue from '../models/Issue.js'; import Comment from '../models/Comment.js'; import Notification from '../models/Notification.js'; import ActivityLog from '../models/ActivityLog.js'; import Milestone from '../models/Milestone.js'; import Label from '../models/Label.js'; import Workspace from '../models/Workspace.js'; import WorkspaceMember from '../models/WorkspaceMember.js'; import CalendarEvent from '../models/CalendarEvent.js'; import ChatMessage from '../models/ChatMessage.js';
await connectDB();
await Promise.all([User.deleteMany({}),Workspace.deleteMany({}),WorkspaceMember.deleteMany({}),Project.deleteMany({}),ProjectMember.deleteMany({}),Task.deleteMany({}),Sprint.deleteMany({}),Issue.deleteMany({}),Comment.deleteMany({}),Notification.deleteMany({}),ActivityLog.deleteMany({}),Milestone.deleteMany({}),Label.deleteMany({}),CalendarEvent.deleteMany({}),ChatMessage.deleteMany({})]);
const pw=async x=>bcrypt.hash(x,12);
const users=await User.create([
 {name:'Meigirishwar V R',email:'admin@nexora.com',password:await pw('Admin@123'),role:'ADMIN',department:'IT',jobTitle:'Workspace Administrator',bio:'Workspace owner and delivery administrator.',skills:['Leadership','Project Planning','MongoDB']},
 {name:'Lokesh V',email:'lokesh@nexora.com',password:await pw('Lokesh@123'),role:'PROJECT_MANAGER',department:'Engineering',jobTitle:'Project Manager',bio:'Coordinates projects, sprints and delivery.',skills:['Planning','Agile','Delivery']},
 {name:'Midhun J S',email:'midhun@nexora.com',password:await pw('Midhun@123'),role:'DEVELOPER',department:'Engineering',jobTitle:'Software Developer',bio:'Builds product features and integrations.',skills:['React','Node.js','MongoDB']},
 {name:'Nithesh Kumar M',email:'nithesh@nexora.com',password:await pw('Nithesh@123'),role:'DEVELOPER',department:'Engineering',jobTitle:'Software Developer',bio:'Works on frontend and backend delivery.',skills:['Express','JavaScript','APIs']},
 {name:'Mariyappa Raja',email:'mariyappa@nexora.com',password:await pw('Mariyappa@123'),role:'TESTER',department:'Quality Assurance',jobTitle:'QA Tester',bio:'Validates releases and tracks product quality.',skills:['Testing','API Testing','Bug Tracking']},
 {name:'Meghaa',email:'meghaa@nexora.com',password:await pw('Meghaa@123'),role:'GUEST',department:'Business',jobTitle:'Guest / Stakeholder',bio:'Workspace guest with read-only visibility.',skills:['Review','Feedback']}
]);
const [admin,pm,dev1,dev2,tester,guest]=users;
const workspace=await Workspace.create({name:'NEXORA Demo Workspace',slug:'nexora-demo-workspace',description:'NEXORA unified software project management workspace.',owner:admin._id});
await WorkspaceMember.create([
 {workspace:workspace._id,user:admin._id,role:'ADMIN'}, {workspace:workspace._id,user:pm._id,role:'PROJECT_MANAGER'}, {workspace:workspace._id,user:dev1._id,role:'DEVELOPER'}, {workspace:workspace._id,user:dev2._id,role:'DEVELOPER'}, {workspace:workspace._id,user:tester._id,role:'TESTER'}, {workspace:workspace._id,user:guest._id,role:'GUEST'}
]);
const projects=await Project.create([
 {workspace:workspace._id,name:'NEXORA Platform',key:'NEX',description:'Unified project management and collaboration platform.',manager:pm._id,members:users.map(u=>u._id),startDate:new Date('2026-09-01'),endDate:new Date('2026-12-20'),status:'Active',priority:'High',technology:['React','Node.js','MongoDB','Socket.IO'],category:'SaaS'},
 {workspace:workspace._id,name:'E-Commerce Application',key:'ECO',description:'Modern commerce workflow and secure checkout experience.',manager:pm._id,members:[pm._id,dev1._id,dev2._id,tester._id],startDate:new Date('2026-09-10'),endDate:new Date('2026-11-30'),status:'Planning',priority:'Medium',technology:['React','Express','MongoDB'],category:'Web'},
 {workspace:workspace._id,name:'Mobile Banking System',key:'MBS',description:'Secure banking workflow prototype.',manager:pm._id,members:[pm._id,dev1._id,tester._id],startDate:new Date('2026-08-15'),endDate:new Date('2026-10-15'),status:'On Hold',priority:'Critical',technology:['React','Node.js'],category:'FinTech'}
]);
for(const p of projects)for(const u of p.members)await ProjectMember.create({project:p._id,user:u,role:String(u)===String(pm._id)?'PROJECT_MANAGER':String(u)===String(tester._id)?'TESTER':String(u)===String(guest._id)?'GUEST':'DEVELOPER'});
const sprints=await Sprint.create([{name:'Sprint 1 — Foundation',goal:'Authentication and core workspace',project:projects[0]._id,startDate:new Date('2026-09-01'),endDate:new Date('2026-09-14'),status:'Completed'},{name:'Sprint 2 — Collaboration',goal:'Kanban, issues and chat',project:projects[0]._id,startDate:new Date('2026-09-15'),endDate:new Date('2026-09-28'),status:'Active'},{name:'Commerce Discovery',goal:'Plan commerce workflows',project:projects[1]._id,startDate:new Date('2026-09-25'),endDate:new Date('2026-10-10'),status:'Planned'}]);
const tasks=await Task.create([{taskId:'TASK-101',title:'Implement workspace authentication',description:'Build secure login and protected routes.',project:projects[0]._id,sprint:sprints[0]._id,assignee:dev1._id,reporter:pm._id,priority:'High',status:'Done',estimatedHours:8,actualHours:7,dueDate:new Date('2026-09-14'),labels:['backend','security']},{taskId:'TASK-102',title:'Build real-time team chat',description:'Implement group chat, mentions and notifications.',project:projects[0]._id,sprint:sprints[1]._id,assignee:dev1._id,reporter:pm._id,priority:'Critical',status:'In Progress',estimatedHours:12,dueDate:new Date('2026-09-26'),labels:['realtime']},{taskId:'TASK-103',title:'Build project detail workflow',description:'Create view and edit controls for project details.',project:projects[0]._id,sprint:sprints[1]._id,assignee:dev2._id,reporter:pm._id,priority:'Medium',status:'In Review',estimatedHours:6,dueDate:new Date('2026-09-27'),labels:['frontend']},{taskId:'TASK-104',title:'Regression test authentication',project:projects[0]._id,sprint:sprints[1]._id,assignee:tester._id,reporter:pm._id,priority:'High',status:'To Do',estimatedHours:5,dueDate:new Date('2026-09-28'),labels:['qa']},{taskId:'TASK-201',title:'Checkout data model',project:projects[1]._id,assignee:dev2._id,reporter:pm._id,priority:'Medium',status:'Backlog',estimatedHours:10,dueDate:new Date('2026-10-05')}]);
const issues=await Issue.create([{issueId:'BUG-41',title:'Login validation error on empty email',description:'Client and server should return clear validation.',project:projects[0]._id,reporter:tester._id,assignee:dev1._id,type:'Bug',priority:'High',severity:'Major',status:'Resolved',environment:'Windows / Chrome',stepsToReproduce:'Submit login with blank email',expectedResult:'Inline validation',actualResult:'Generic error'},{issueId:'BUG-42',title:'Kanban card loses order after refresh',description:'Persist task ordering after reload.',project:projects[0]._id,reporter:tester._id,assignee:dev2._id,type:'Bug',priority:'Medium',severity:'Minor',status:'Open',environment:'Windows / Edge'}]);
await Comment.create([{author:pm._id,project:projects[0]._id,task:tasks[1]._id,message:'Please make the drag/drop state persistent.'},{author:tester._id,project:projects[0]._id,issue:issues[0]._id,message:'Retested on latest build; fix is behaving correctly.'}]);
await Milestone.create([{name:'MVP Release',description:'Core workspace demo-ready.',project:projects[0]._id,startDate:new Date('2026-09-01'),dueDate:new Date('2026-10-01'),status:'In Progress',progress:68},{name:'Commerce Discovery',project:projects[1]._id,dueDate:new Date('2026-10-20'),status:'Upcoming',progress:15}]);
await Label.create([{name:'frontend',color:'#2563EB',project:projects[0]._id},{name:'backend',color:'#06B6D4',project:projects[0]._id},{name:'qa',color:'#16A34A',project:projects[0]._id}]);
await Notification.create([{workspace:workspace._id,user:dev1._id,type:'task_assigned',message:'You were assigned TASK-102: Build real-time team chat',link:'/tasks'},{workspace:workspace._id,user:tester._id,type:'issue_updated',message:'BUG-41 has been resolved and is ready for verification',link:'/issues'}]);
await ChatMessage.create([{workspace:workspace._id,sender:pm._id,message:'Welcome everyone. Use this chat for delivery updates, questions and @mentions.',mentions:[]},{workspace:workspace._id,sender:dev1._id,message:'I am working on the real-time chat and notifications.',mentions:[]}]);
await CalendarEvent.create([{workspace:workspace._id,createdBy:pm._id,title:'Sprint 2 review',description:'Review collaboration module progress with the team.',startAt:new Date('2026-09-28T16:00:00'),endAt:new Date('2026-09-28T17:00:00'),allDay:false},{workspace:workspace._id,createdBy:admin._id,title:'MVP checkpoint',description:'Workspace-wide delivery checkpoint.',startAt:new Date('2026-10-01T10:00:00'),endAt:new Date('2026-10-01T11:00:00'),allDay:false}]);
for(const p of projects)await ActivityLog.create({actor:pm._id,workspace:workspace._id,project:p._id,action:'created project',objectType:'Project',objectId:p._id});
await ActivityLog.create({actor:dev1._id,workspace:workspace._id,project:projects[0]._id,action:'moved TASK-101 from In Progress to Done',objectType:'Task',objectId:tasks[0]._id});
await ActivityLog.create({actor:admin._id,workspace:workspace._id,action:'seeded NEXORA workspace',objectType:'Workspace',objectId:workspace._id});
console.log('Seed complete. Workspace: NEXORA Demo Workspace');
console.log('Credentials:');
for(const u of [{email:'admin@nexora.com',password:'Admin@123',role:'ADMIN'},{email:'lokesh@nexora.com',password:'Lokesh@123',role:'PROJECT_MANAGER'},{email:'midhun@nexora.com',password:'Midhun@123',role:'DEVELOPER'},{email:'nithesh@nexora.com',password:'Nithesh@123',role:'DEVELOPER'},{email:'mariyappa@nexora.com',password:'Mariyappa@123',role:'TESTER'},{email:'meghaa@nexora.com',password:'Meghaa@123',role:'GUEST'}])console.log(`${u.role}: ${u.email} / ${u.password}`);
await mongoose.disconnect();
