import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import nodemailer from 'nodemailer';
import User from '../models/User.js';
import WorkspaceMember from '../models/WorkspaceMember.js';
import { logActivity } from '../services/activityService.js';
const token=u=>jwt.sign({id:u._id},process.env.JWT_SECRET,{expiresIn:'7d'});
const safe=u=>u.toObject({transform:(d,r)=>{delete r.password;delete r.resetToken;delete r.resetTokenExpires;return r;}});
export async function register(req,res,next){try{const {name,email,password,confirmPassword}=req.body;if(!name||!email||!password||password!==confirmPassword)return res.status(400).json({message:'Valid name, email and matching passwords are required'});if(password.length<8)return res.status(400).json({message:'Password must be at least 8 characters'});if(await User.findOne({email:email.toLowerCase()}))return res.status(409).json({message:'Email already registered'});const hash=await bcrypt.hash(password,12);const user=await User.create({name,email:email.toLowerCase(),password:hash});res.status(201).json({token:token(user),user:safe(user)});}catch(e){next(e)}}
export async function login(req,res,next){try{const {email,password}=req.body;const user=await User.findOne({email:email?.toLowerCase().trim()});if(!user||!await bcrypt.compare(password,user.password))return res.status(401).json({message:'Invalid email or password'});user.lastSeen=new Date();await user.save();const memberships=await WorkspaceMember.find({user:user._id,status:'ACTIVE'}).populate('workspace','name slug description owner active createdAt');await Promise.all(memberships.map(m=>logActivity({actor:user._id,workspace:m.workspace._id,action:'logged in',objectType:'User',objectId:user._id})));res.json({token:token(user),user:safe(user),workspaces:memberships.map(m=>({...m.workspace.toObject(),role:m.role}))});}catch(e){next(e)}}
export async function me(req,res){res.json(req.user)}
export async function changeCredentials(req,res,next){try{const {currentPassword,newPassword,newEmail}=req.body;const user=await User.findById(req.user._id);if(!currentPassword||!await bcrypt.compare(currentPassword,user.password))return res.status(400).json({message:'Current password is incorrect'});if(newEmail&&newEmail.toLowerCase()!==user.email){const exists=await User.exists({email:newEmail.toLowerCase()});if(exists)return res.status(409).json({message:'That email is already in use'});user.email=newEmail.toLowerCase().trim();}if(newPassword){if(newPassword.length<8)return res.status(400).json({message:'New password must be at least 8 characters'});user.password=await bcrypt.hash(newPassword,12);}await user.save();res.json({message:'Credentials updated',user:safe(user),token:token(user)});}catch(e){next(e)}}
function mailer(){return nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}})}
export async function forgotPassword(req,res,next){try{const email=req.body.email?.toLowerCase().trim();if(!email)return res.status(400).json({message:'Email is required'});const user=await User.findOne({email});if(!user)return res.json({message:'If the account exists, a reset email has been sent.'});if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS)return res.status(503).json({message:'Password reset email is not configured on this server yet.'});const raw=crypto.randomBytes(32).toString('hex');user.resetToken=crypto.createHash('sha256').update(raw).digest('hex');user.resetTokenExpires=new Date(Date.now()+30*60*1000);await user.save();const base=process.env.CLIENT_URL||'http://localhost:5173';const link=`${base}/login?reset=${raw}`;await mailer().sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:user.email,subject:'NEXORA password reset',text:`Reset your NEXORA password within 30 minutes: ${link}`});res.json({message:'If the account exists, a reset email has been sent.'});}catch(e){next(e)}}
export async function resetPassword(req,res,next){try{const raw=req.body.token;const user=await User.findOne({resetToken:crypto.createHash('sha256').update(raw||'').digest('hex'),resetTokenExpires:{$gt:new Date()}});if(!user)return res.status(400).json({message:'Reset link is invalid or expired'});if(!req.body.password||req.body.password.length<8)return res.status(400).json({message:'Password must be at least 8 characters'});user.password=await bcrypt.hash(req.body.password,12);user.resetToken=undefined;user.resetTokenExpires=undefined;await user.save();res.json({message:'Password reset successfully'});}catch(e){next(e)}}
